# Index embeddings into embedding store

# Set up

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
import sys

import torch
import pandas as pd
from dotenv import load_dotenv
from loguru import logger
from pydantic import BaseModel
from qdrant_client import QdrantClient
from qdrant_client.models import Distance, PointStruct, VectorParams

import mlflow

sys.path.insert(0, "..")

from src.cfg import ConfigLoader

load_dotenv()

True

# Controller

In [3]:
cfg = ConfigLoader("../cfg/common.yaml")
cfg

{
  "run": {
    "author": "",
    "testing": false,
    "log_to_mlflow": true,
    "experiment_name": null,
    "run_name": null,
    "run_persist_dir": null,
    "random_seed": 41
  },
  "data": {
    "hf_datasets": {
      "name": "McAuley-Lab/Amazon-Reviews-2023",
      "mcauley_variant": "Books"
    },
    "train_fp": "/home/dvq/frostmourne/recsys-blog/1-seq-model/data/train.parquet",
    "val_fp": "/home/dvq/frostmourne/recsys-blog/1-seq-model/data/val.parquet",
    "idm_fp": "/home/dvq/frostmourne/recsys-blog/1-seq-model/data/idm.json",
    "metadata_fp": "/home/dvq/frostmourne/recsys-blog/1-seq-model/data/metadata.parquet",
    "train_features_fp": "/home/dvq/frostmourne/recsys-blog/1-seq-model/data/train_features.parquet",
    "val_features_fp": "/home/dvq/frostmourne/recsys-blog/1-seq-model/data/val_features.parquet",
    "full_features_neg_fp": "/home/dvq/frostmourne/recsys-blog/1-seq-model/data/full_features_neg_sampling_df.parquet",
    "train_features_neg_fp": "/home/dvq/frostmourne/recsys-blog/1-seq-model/data/train_features_neg_df.parquet",
    "val_features_neg_fp": "/home/dvq/frostmourne/recsys-blog/1-seq-model/data/val_features_neg_df.parquet",
    "user_col": "user_id",
    "item_col": "parent_asin",
    "rating_col": "rating",
    "timestamp_col": "timestamp"
  },
  "sample": {
    "sample_users": 10000,
    "min_val_records": 5000,
    "min_user_interactions": 5,
    "min_item_interactions": 10
  },
  "train": {
    "label_format": "binary",
    "learning_rate": 0.001,
    "batch_size": 128,
    "max_epochs": 100,
    "early_stopping_patience": 5,
    "device": null,
    "embedding_dim": 128,
    "dropout": 0.0,
    "l2_reg": 1e-05,
    "retriever": {
      "model_classname": "TwoTowerSequenceRetriever",
      "mlf_model_name": "sequence_retriever"
    },
    "sequence": {
      "sequence_length": 10
    }
  },
  "eval": {
    "top_k_retrieve": 100,
    "top_k_rerank": 10,
    "min_roc_auc": 0.7
  },
  "vectorstore": {
    "qdrant": {
      "classname": "QdrantVectorStore",
      "url": "localhost:6333",
      "collection_name": "seq_model_retrieve"
    }
  }
}

# Load model

In [4]:
mlf_client = mlflow.MlflowClient()

In [5]:
mlf_model = mlflow.pyfunc.load_model(model_uri=f"models:/{cfg.train.retriever.mlf_model_name}@champion")

Downloading artifacts:   0%|          | 0/8 [00:00<?, ?it/s]

/home/dvq/frostmourne/recsys-blog/1-seq-model/.venv/lib/python3.11/site-packages/mlflow/pyfunc/utils/data_validation.py:168: UserWarning: Add type hints to the `predict` method to enable data validation and automatic signature inference during model logging. Check https://mlflow.org/docs/latest/model/python_model.html#type-hint-usage-in-pythonmodel for more details.
  color_warning(

In [6]:
run_id = mlf_model.metadata.run_id
run_info = mlf_client.get_run(run_id).info
artifact_uri = run_info.artifact_uri

In [7]:
sample_input = mlflow.artifacts.load_dict(f"{artifact_uri}/inferrer/input_example.json")
sample_input

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

{'user_ids_raw': ['AE224PFXAEAT66IXX43GRJSWHXCA'],
 'item_seq_raw': [['0007149824', '0007149832']],
 'candidate_items_raw': ['0007149824']}

In [ ]:
prediction = mlf_model(sample_input)
prediction

/home/dvq/frostmourne/recsys-blog/1-seq-model/notebooks/../src/sequence/inference.py:68: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at /pytorch/torch/csrc/utils/tensor_new.cpp:254.)
  item_sequences = torch.tensor(item_sequences)

{'user_ids_raw': ['AE224PFXAEAT66IXX43GRJSWHXCA'],
 'item_seq_raw': [['0007149824', '0007149832']],
 'candidate_items_raw': ['0007149824'],
 'scores': [0.5968694686889648]}

# Get embeddings

In [9]:
inferer = mlf_model.unwrap_python_model()
id_mapping = inferer.idm
all_items = list(id_mapping.item_to_index.values())
num_items = len(all_items)
logger.info(f"{all_items[:5]=}, {num_items=:,.0f}")

2025-03-11 20:11:41.751 | INFO     | __main__:<module>:5 - all_items[:5]=[0, 1, 2, 3, 4], num_items=7,388

In [11]:
model = inferer.model
model.eval()

all_item_ids = torch.arange(num_items)
inputs = {
    "candidate_items": all_item_ids
}

with torch.no_grad():
    candidate_embeddings = model.get_candidate_embeddings(inputs).detach().numpy()

embedding_dim = candidate_embeddings.shape[1]
logger.info(f"{embedding_dim=}")
candidate_embeddings[0]

2025-03-11 20:12:39.423 | INFO     | __main__:<module>:13 - embedding_dim=128

array([-0.10703436, -0.17216803, -0.709746  , -0.36154547,  0.0796136 ,
        0.68052334, -0.41148958,  0.6020838 , -0.6856135 , -0.76566297,
        0.80649155,  0.11452065,  0.36899605,  0.5482804 , -0.2100071 ,
        0.7301396 ,  0.21019037,  0.14870211,  0.10973708,  0.12490606,
       -0.81939036,  0.4751542 ,  0.8970341 ,  0.3210783 ,  0.2444923 ,
       -0.45022163, -0.6635965 ,  0.05767518,  0.83844936, -0.2673742 ,
       -0.31369504, -0.8094832 ,  0.8129729 , -0.07270477,  0.01270208,
       -1.3898419 , -0.18922094, -0.16148195,  0.6341016 ,  0.8318451 ,
        0.04122666, -0.59477454, -0.31984943, -0.14195304, -0.8827549 ,
       -0.17894791, -0.10703595,  1.311721  , -1.0553167 , -0.5977145 ,
        1.1542509 ,  0.27556774, -0.589627  ,  0.08037068, -0.07314882,
        0.56439096,  0.64440215,  0.4762257 , -0.11130129,  0.3758156 ,
       -0.24041894, -0.00555591, -0.5684053 ,  0.06658808,  0.3106705 ,
        0.48493612, -0.4813773 , -0.7402723 , -0.00522922,  0.2029313 ,
        0.07853644,  0.13603939,  0.14666976, -0.01621578,  0.7369242 ,
        0.41692945,  0.45439854, -1.0184877 , -0.14473133,  0.7225807 ,
        0.18682055,  0.6454927 , -0.47569913,  1.3707111 , -0.28779837,
       -0.27852893,  0.53728545, -0.11185958,  0.06843577, -1.061879  ,
        0.74569815,  0.5151374 , -0.57826656,  1.1089271 , -0.05595297,
        0.64089566,  0.19951645,  0.19722253,  0.7407622 ,  0.504967  ,
       -0.8286159 , -0.26525787, -0.9871688 ,  0.5058175 , -0.38918114,
        0.68936276,  0.3149896 ,  0.20326804,  0.20628482,  0.29118013,
        0.15160728, -0.15117653,  1.9051828 ,  0.23121168, -0.59339213,
       -0.7124532 ,  0.2099021 ,  0.05851636,  0.5224884 ,  0.46718308,
       -0.7047523 ,  0.54405826, -0.5390125 ,  0.36198372,  1.0151674 ,
        0.47573295,  0.83965015, -0.35009512], dtype=float32)

In [12]:
candidate_embeddings.shape

(7388, 128)

# Load item meta

In [13]:
metadata_df = pd.read_parquet(cfg.data.metadata_fp)
metadata_df

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,Buy a Kindle,The Alibi,4.3,5532,"[In this suspenseful Southern thriller and #1,...","[Amazon.com Review, Sandra Brown's two previou...",7.99,"{'hi_res': [None], 'large': ['https://m.media-...","{'title': [], 'url': [], 'user_id': []}",Sandra Brown (Author) Format: Kindle Edition,"[Books, Mystery, Thriller & Suspense, Thriller...","{""Publisher"": ""Grand Central Publishing (Augus...",B00BEK6ZR2,None,Kindle Edition,{'avatar': 'https://m.media-amazon.com/images/...
1,Buy a Kindle,Later,4.5,33092,"[“Part detective tale, part thriller…touching ...","[Review, #1 on The New York Times bestselling ...",9.99,"{'hi_res': [None], 'large': ['https://m.media-...","{'title': [], 'url': [], 'user_id': []}",Stephen King (Author) Format: Kindle Edition,"[Books, Mystery, Thriller & Suspense, Thriller...","{""Publisher"": ""Hard Case Crime (March 2, 2021)...",B08F4GYM8W,None,Kindle Edition,{'avatar': 'https://m.media-amazon.com/images/...
2,Buy a Kindle,The Night Agent: A Novel,4.4,2731,[NOW ON NETFLIX! Starring Gabriel Basso and Lu...,"[Review, “, The Night Agent, is a whirlwind of...",8.99,"{'hi_res': [None], 'large': ['https://m.media-...","{'title': [], 'url': [], 'user_id': []}",Matthew Quirk (Author) Format: Kindle Edition,"[Books, Mystery, Thriller & Suspense, Thriller...","{""Publisher"": ""William Morrow (January 15, 201...",B07B7LB9TN,None,Kindle Edition,{'avatar': 'https://m.media-amazon.com/images/...
3,Buy a Kindle,The Word Is Murder: A Novel (A Hawthorne and H...,4.3,15516,"[""One of the most entertaining mysteries of th...","[From the Back Cover, One bright spring mornin...",14.49,"{'hi_res': [None], 'large': ['https://m.media-...",{'title': ['The Word Is Murder: A Novel (Detec...,Anthony Horowitz (Author) Format: Kindle Edi...,"[Books, Mystery, Thriller & Suspense, Thriller...","{""Publisher"": ""Harper; Reprint edition (June 5...",B072PQXYYJ,None,Kindle Edition,{'avatar': 'https://m.media-amazon.com/images/...
4,Buy a Kindle,The Hard Way Home (The Star and the Shamrock B...,4.7,10964,[Dublin 1950Liesl Bannon has never felt like s...,[],0.0,"{'hi_res': [None], 'large': ['https://m.media-...","{'title': [], 'url': [], 'user_id': []}",Jean Grainger (Author) Format: Kindle Edition,"[Books, Literature & Fiction, Genre Fiction]","{""Publication date"": ""June 29, 2020"", ""Languag...",B088HJ5312,None,Kindle Edition,{'avatar': 'https://m.media-amazon.com/images/...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7383,Books,Adult Coloring Book: Stress Relieving Patterns,4.5,4342,[STRESS RELIEVING | CALMING | RELAXING | CREAT...,[],6.91,"{'hi_res': [], 'large': [], 'thumb': [], 'vari...","{'title': [], 'url': [], 'user_id': []}","Blue Star Coloring (Author), Adult Coloring B...","[Books, Arts & Photography, History & Criticism]","{""Publisher"": ""Blue Star Coloring; Csm edition...",1941325122,None,"Paperback – March 28, 2015",{'avatar': 'https://m.media-amazon.com/images/...
7384,Books,Code Name Verity (Edgar Allen Poe Awards. Best...,4.3,5426,"[The beloved #1, New York Times, bestseller, a...","[Amazon.com Review, Amazon Best Teen Books of ...",9.19,"{'hi_res': [], 'large': [], 'thumb': [], 'vari...","{'title': [], 'url': [], 'user_id': []}",Elizabeth Wein (Author),"[Books, Teen & Young Adult, Literature & Fiction]","{""Publisher"": ""Little, Brown Books for Young R...",1423152190,None,"Hardcover – May 15, 2012",{'avatar': 'https://m.media-amazon.com/images/...
7385,Buy a Kindle,Cold Vengeance (Pendergast Book 11),4.6,3552,"[Twelve years ago, Special Agent Pendergast's ...","[Review, An exceptionally strong number of a b...",8.99,"{'hi_res': [], 'large': [], 'thumb': [], 'vari...","{'title': [], 'url': [], 'user_id': []}","Douglas Preston (Author), Lincoln Child (Auth...","[Books, Literature & Fiction, Genre Fiction]","{""Publisher"": ""Grand Central Publishing (Augus...",B0048EKF3Q,None,Kindle Edition,{'avatar': 'https://m.media-amazon.com/images/...
7386,Buy a Kindle,Ghost Fleet: A Novel of the Next World War,4.2,7400,"[""A novel that reads like science fiction but ...",[Excerpt. © Reprinted by permission. All right...,12.99,"{'hi_res': [], 'large': [], 'thumb': [], 'vari...","{'title': [], 'url': [], 'user_id': []}","P. W. Singer (Author), August Cole (Author) ...","[Books, Mystery, Thriller & Suspense, Thriller...","{""Publisher"": ""Mariner Books; Reprint edition ...",B00LZ7GOI4,None,Kindle Edition,{'avatar': 'https://m.media-amazon.com/images/...
7387,Books,The Lost City of Z: A Tale of Deadly Obsession...,4.3,8580,[A grand mystery reaching back centuries. A se...,"[Amazon.com Review, Amazon Exclusive: John Gri...",34.58,"{'hi_res': [], 'large': [], 'thumb': [], 'vari...","{'title': [], 'url': [], 'user_id': []}",David Grann (Author),"[Books, History, Americas]","{""Publisher"": ""Doubleday (February 24, 2009)"",...",0385513534,None,"Hardcover – February 24, 2009",{'avatar': 'https://m.media-amazon.com/images/...

In [14]:
metadata_cols = [
    'main_category',
    'title',
    'average_rating',
    'rating_number',
    'price',
    cfg.data.item_col,
    'subtitle'
]
metadata_map = metadata_df[metadata_cols].set_index(cfg.data.item_col).to_dict(orient='index')
len(metadata_map)

7388

# Embedding store

In [15]:
ann_index = QdrantClient(url=cfg.vectorstore.qdrant.url)

In [16]:
collection_exists = ann_index.collection_exists(cfg.vectorstore.qdrant.collection_name)
if collection_exists:
    logger.info(f"Deleting existing Qdrant collection {cfg.vectorstore.qdrant.collection_name}...")
    ann_index.delete_collection(cfg.vectorstore.qdrant.collection_name)

logger.info(f"Creating Qdrant collection {cfg.vectorstore.qdrant.collection_name}...")
create_collection_result = ann_index.create_collection(
    collection_name=cfg.vectorstore.qdrant.collection_name,
    vectors_config=VectorParams(size=embedding_dim, distance=Distance.COSINE),
)

assert create_collection_result == True

2025-03-11 20:15:00.910 | INFO     | __main__:<module>:3 - Deleting existing Qdrant collection seq_model_retrieve...
2025-03-11 20:15:00.916 | INFO     | __main__:<module>:6 - Creating Qdrant collection seq_model_retrieve...

In [17]:
points = []
for idx, vector in enumerate(candidate_embeddings):
    id_ = id_mapping.get_item_id(idx)
    payload = metadata_map[id_]
    point = PointStruct(id=idx, vector=vector.tolist(), payload=payload)
    points.append(point)

upsert_result = ann_index.upsert(
    collection_name=cfg.vectorstore.qdrant.collection_name,
    points=points,
)
assert str(upsert_result.status) == "completed"
upsert_result

UpdateResult(operation_id=0, status=<UpdateStatus.COMPLETED: 'completed'>)

# Sanity check

In [18]:
metadata_df.loc[metadata_df['title'].str.contains("(?i)harry potter", regex=True)]

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
117,Books,Harry Potter and the Order of the Phoenix (Boo...,4.8,75559,"[The next volume in the thrilling, moving, bes...","[Amazon.com Review, As his fifth year at Hogwa...",17.29,"{'hi_res': [None], 'large': ['https://m.media-...",{'title': ['Customer Review: wish I knew this ...,"J. K. Rowling (Author), Mary GrandPré (Illust...","[Books, Children's Books, Growing Up & Facts o...","{""Publisher"": ""Arthur A. Levine Books; First E...",043935806X,None,"Hardcover – July 1, 2003",{'avatar': 'https://m.media-amazon.com/images/...
139,Books,Harry Potter and the Prisoner of Azkaban (Harr...,4.9,80540,"[For twelve long years, the dread fortress of ...","[Amazon.com Review, For most children, summer ...",15.74,"{'hi_res': [None], 'large': ['https://m.media-...",{'title': ['Harry Potter Prisoner of Azkaban B...,"J.K. Rowling (Author), Mary GrandPré (Illustr...","[Books, Children's Books, Growing Up & Facts o...","{""Publisher"": ""Scholastic; First Edition (Octo...",0439136350,None,"Hardcover – October 1, 1999",{'avatar': 'https://m.media-amazon.com/images/...
257,Books,Harry Potter and the Sorcerer's Stone (1),4.9,8716,[Harry Potter spent ten long years living with...,"[Amazon.com Review, Say you've spent the first...",15.69,"{'hi_res': [None], 'large': ['https://m.media-...",{'title': ['Cutomer Review: Why should you get...,"J.K. Rowling (Author), Mary Grandpre (Illustr...","[Books, Children's Books, Growing Up & Facts o...","{""Publisher"": ""Scholastic Press (October 1, 19...",0590353403,None,"Hardcover – October 1, 1998",{'avatar': 'https://m.media-amazon.com/images/...
704,Books,Harry Potter and the Chamber of Secrets: The I...,4.9,14496,[Award-winning artist Jim Kay illustrates year...,"[Review, ""Seeing Jim Kay's illustrations moved...",23.63,"{'hi_res': [None], 'large': ['https://m.media-...",{'title': ['Check out what is inside this book...,"J. K. Rowling (Author), Mr. Jim Kay (Illustra...","[Books, Children's Books, Growing Up & Facts o...","{""Publisher"": ""Arthur A. Levine Books; Illustr...",0545791324,None,"Hardcover – Illustrated, October 4, 2016",{'avatar': 'https://m.media-amazon.com/images/...
1198,Books,"Harry Potter and the Cursed Child, Parts 1 & 2...",4.3,100137,"["", The Eighth Story. Nineteen Years Later., B...","[From School Library Journal, Playwright Thorn...",9.29,"{'hi_res': [None], 'large': ['https://m.media-...","{'title': [], 'url': [], 'user_id': []}","J.K. Rowling (Author), Jack Thorne (Author), ...","[Books, Children's Books, Science Fiction & Fa...","{""Publisher"": ""Arthur A. Levine Books; Special...",1338099132,None,"Hardcover – July 31, 2016",{'avatar': 'https://m.media-amazon.com/images/...
1389,Books,Harry Potter Hardcover Boxed Set: Books 1-7,4.9,111418,[HARRY POTTER BOXED SET 1-7 includes the seven...,"[About the Author, J.K. ROWLING is the author ...",154.09,"{'hi_res': [None], 'large': ['https://m.media-...","{'title': ['Perfect condition!', 'Great condit...",J. K. Rowling (Author),"[Books, Teen & Young Adult, Science Fiction & ...","{""Publisher"": ""Scholastic Inc.; First Thus edi...",0545044251,None,"Hardcover – Box set, October 16, 2007",{'avatar': 'https://m.media-amazon.com/images/...
1406,Books,Harry Potter and the Half-Blood Prince (Book 6),4.9,71339,[As the Harry Potter sequence draws to a close...,"[Amazon.com Review, The long-awaited, eagerly ...",16.11,"{'hi_res': [None], 'large': ['https://m.media-...",{'title': ['Harry Potter Half-Blood Prince Boo...,"J. K. Rowling (Author), Mary GrandPré (Illust...","[Books, Children's Books, Growing Up & Facts o...","{""Publisher"": ""Arthur A. Levine Books (August ...",0439784549,None,"Hardcover – August 1, 2005",{'avatar': 'https://m.media-amazon.com/images/...
1564,Books,Harry Potter and the Sorcerer's Stone: The Ill...,4.9,25381,[The beloved first book of the Harry Potter se...,"[From School Library Journal, Gr 4–7—Whether t...",21.99,"{'hi_res': [None], 'large': ['https://m.media-...","{'title': ['You NEED To Check This Out!! ', 'C...","J.K. Rowling (Author), Jim Kay (Illustrator)","[Books, Children's Books, Growing Up & Facts o...","{""Publisher"": ""Arthur A. Levine Books; Illustr...",0545790352,None,"Hardcover – Illustrated, October 6, 2015",{'avatar': 'https://m.media-amazon.com/images/...
1569,Books,Harry Potter and the Chamber of Secrets,4.8,85813,[The summer after his first year at Hogwarts i...,"[Amazon.com Review, It's hard to fall in love ...",6.81,"{'hi_res': [None], 'large': ['https://m.media-...",{'title': ['Harry Potter and the Chamber of Se...,"J.K. Rowling (Author), Mary GrandPré (Illustr...","[Books, Children's Books, Growing Up & Facts o...","{""Publisher"": ""Scholastic (July 1, 1999)"", ""La...",0439064864,None,"Hardcover – Big Book, July 1, 1999",{'avatar': 'https://m.media-amazon.com/images/...
2766,Books,Harry Potter and the Deathly Hallows (Book 7),4.9,86804,[The magnificent final book in J. K. Rowling's...,"[Amazon.com Review, Readers beware. The brilli...",18.41,"{'hi_res': [None], 'large': ['https://m.media-...",{'title': ['Customer Review: Is it worth it? '...,"J. K. Rowling (Author), Mary GrandPré (Illust...","[Books, Children's Books, Science Fiction & Fa...","{""Publisher"": ""Arthur A. Levine Books (August ...",0545010225,None,"Hardcover – August 1, 2007",{'avatar': 'https://m.media-amazon.com/images/...
2875,Books,Harry Potter and the Sorcerer's Stone,4.8,5277,[Harry Potter has no idea how famous he is. Th...,"[From Publishers Weekly, The breakaway bestsel...",6.98,"{'hi_res': [], 'large': [], 'thumb': [], 'vari...",{'title': ['Highly Recommend Harry Potter and ...,"J.K. Rowling (Author), Mary GrandPré (Illustr...","[Books, Children's Books, Growing Up & Facts o...","{""Publisher"": ""Scholastic; 1st edition (Septem...",059035342X,None,"Paperback – September 1, 1998",{'avatar': 'https://m.media-amazon.com/images/...
3320,Books,Harry Potter and the Deathly Hallows (Harry Po...,4.9,87039,"[Readers beware. The brilliant, breathtaking c...","[About the Author, J.K. ROWLING is the author ...",5.93,"{'hi_res': [None], 'large': ['https://m.media-...",{'title': ['Harry Potter and the Deathly Hallo...,J. K. Rowling (Author),"[Books, Children's Books, Growing Up & Facts o...","{""Publisher"": ""Scholastic Inc. (July 1, 2009)""...",0545139708,None,"Paperback – July 1, 2009",{'avatar': 'https://m.media-amazon.com/images/...
4114,Books,Harry Potter and the Goblet of Fire (Harry Pot...,4.9,75834,"[The paperback edition of the legendary, recor...","[From Publishers Weekly, In our Best Books cit...",6.11,"{'hi_res': [None], 'large': ['https://m.media-...",{'title': ['Such a Good Read! Harry Potter and...,"J. K. Rowling (Author), Mary GrandPré (Illust...","[Books, Children's Books, Growing Up & Facts o...","{""Publisher"": ""Scholastic Paperbacks (Septembe...",0439139600,None,"Paperback – September 1, 2002",{'avatar': 'https://m.media-amazon.com/images/...
4952,Books,"The Tales of Beedle the Bard, Standard Edition...",4.6,17053,"[The Tales of Beedle the Bard, , a Wizarding c...","[From School Library Journal, Grade 4 Up—Muggl...",None,"{'hi_res': [None], 'large': ['https://m.media-...","{'title': [], 'url': [], 'user_id': []}",J. K. Rowling (Author),"[Books, Children's Books, Fairy Tales, Folk Ta...","{""Publisher"": ""Children's High Level Group; St...",0545128285,None,"Hardcover – December 4, 2008",{'avatar': 'https://m.media-amazon.com/images/...
5256,Books,Harry Potter and the Prisoner of Azkaban (Harr...,4.9,82628,"[For twelve long years, the dread fortress of ...",[],None,"{'hi_res': [None], 'large': ['https://m.media-...","{'title': [], 'url': [], 'user_id': []}","J.K. Rowling (Author), Mary GrandPré (Illustr...","[Books, Children's Books, Growing Up & Facts o...",{},0439136369,None,"Paperback – October 1, 2001",None
5378,Books,Harry Potter and the Prisoner of Azkaban: The ...,4.9,15282,[The third book in the bestselling Harry Potte...,"[Review, Praise for Jim Kay's illustrations:, ...",None,"{'hi_res': [None], 'large': ['https://m.media-...",{'title': ['Check out What Is Inside This Book...,"Mr. Jim Kay (Author, Illustrator), J. K. Rowl...","[Books, Children's Books, Growing Up & Facts o...","{""Publisher"": ""Arthur A. Levine Books; Illustr...",0545791340,None,"Hardcover – Illustrated, October 3, 2017",{'avatar': 'https://m.media-amazon.com/images/...
5890,Books,Harry Potter and the Order of the Phoenix (Har...,4.8,77311,"[In his fifth year at Hogwart's, Harry faces c...","[Amazon.com Review, As his fifth year at Hogwa...",5.94,"{'hi_res': [None], 'large': ['https://m.media-...",{'title': ['Harry Potter and the Order of the ...,J. K. Rowling (Author),"[Books, Children's Books, Growing Up & Facts o...","{""Publisher"": ""Scholastic Paperbacks (Septembe...",0439358078,None,"Paperback – September 1, 2004",{'avatar': 'https://m.media-amazon.com/images/...
5951,Books,Harry Potter and the Goblet of Fire (Harry Pot...,4.9,76466,[If I knew what the book was about I would sur...,"[Amazon.com Review, In, Harry Potter and the G...",18.49,"{'hi_res': [None], 'large': ['https://m.media-...","{'title': ['Best Harry Potter book , great for...","J.K. Rowling (Author), Mary GrandPré (Illustr...","[Books, Children's Books, Growing Up & Facts o...","{""Publisher"": ""Scholastic Press (August 1, 200...",0439139597,None,None,{'avatar': 'https://m.media-amazon.com/images/...
5968,Books,Harry Potter and the Half-Blood Prince (Book 6),4.9,72739,[The war against Voldemort is not going well; ...,"[About the Author, J.K. ROWLING is the author ...",None,"{'hi_res': [None], 'large': ['https://m.media-...",{'title': ['Harry Potter and the Half-Blood Pr...,"J.K. Rowling (Author), Mary GrandPré (Illustr...","[Books, Children's Books, Growing Up & Facts o...","{""Publisher"": ""Scholastic Paperbacks; Reprint ...",0439785960,None,"Paperback – July 25, 2006",{'avatar': 'https://m.media-amazon.com/images/...
6235,Books,Harry Potter Paperback Box Set (Books 1-7),4.9,113539,"[Now for the first time ever, J.K. Rowling’s s...","[About the Author, J.K. ROWLING is the author ...",45.44,"{'hi_res': [None], 'large': ['https://m.media-...",{'title': ['Is This Box Set Actually Quality? ...,"J. K. Rowling (Author), Mary GrandPré (Illus...","[Books, Children's Books, Growing Up & Facts o...","{""Publisher"": ""Scholastic Inc.; Kindle edition...",0545162076,None,None,{'avatar': 'https://m.media-amazon.com/images/...
6902,Books,Fantastic Beasts and Where to Find Them: The O...,4.6,15170,[J.K. Rowling's screenwriting debut is capture...,"[About the Author, J.K. Rowling is the author ...",13.39,"{'hi_res': [None], 'large': ['https://m.media-...","{'title': [], 'url': [], 'user_id': []}",J.K. Rowling (Author),"[Books, Children's Books, Arts, Music & Photog...","{""Publisher"": ""Arthur A. Levine Books; Illustr...",1338109065,None,"Hardcover – Illustrated, November 18, 2016",{'avatar': 'https://m.media-amazon.com/images/...
7377,Books,Harry Potter Coloring Book,4.8,15833,[Unleash your creativity and escape to one of ...,"[About the Author, Scholastic Inc. is a global...",11.2,"{'hi_res': [], 'large': [], 'thumb': [], 'vari...","{'title': [], 'url': [], 'user_id': []}",Scholastic (Author),"[Books, Children's Books, Arts, Music & Photog...","{""Publisher"": ""Scholastic Inc. (November 10, 2...",1338029991,None,"Paperback – Coloring Book, November 10, 2015",{'avatar': 'https://m.media-amazon.com/images/...

In [46]:
id_ = '043935806X'
idx = id_mapping.get_item_index(id_)
inputs = {
    "item_seq": torch.tensor([[idx]])
}
query_embedding = model.get_query_embeddings(inputs)[0]
logger.info(f"{query_embedding.shape=}")

2025-03-11 20:22:15.497 | INFO     | __main__:<module>:7 - query_embedding.shape=torch.Size([128])

In [47]:
hits = ann_index.search(
    collection_name=cfg.vectorstore.qdrant.collection_name,
    query_vector=query_embedding,
    limit=cfg.eval.top_k_retrieve,
)

/tmp/ipykernel_16404/3324227506.py:1: DeprecationWarning: `search` method is deprecated and will be removed in the future. Use `query_points` instead.
  hits = ann_index.search(

In [48]:
metadata_map[id_]

{'main_category': 'Books',
 'title': 'Harry Potter and the Order of the Phoenix (Book 5)',
 'average_rating': 4.8,
 'rating_number': 75559,
 'price': '17.29',
 'subtitle': 'Hardcover – July 1, 2003'}

In [49]:
hits

[ScoredPoint(id=1381, version=0, score=0.885266, payload={'main_category': 'Books', 'title': 'Harry Potter and the Chamber of Secrets', 'average_rating': 4.8, 'rating_number': 85813, 'price': '6.81', 'subtitle': 'Hardcover – Big Book, July 1, 1999'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=958, version=0, score=0.85394025, payload={'main_category': 'Books', 'title': 'Cutting for Stone: A novel', 'average_rating': 4.6, 'rating_number': 13593, 'price': '39.8', 'subtitle': 'Hardcover – Deckle Edge, February 3, 2009'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=3162, version=0, score=0.8496342, payload={'main_category': 'Books', 'title': 'The Kite Runner', 'average_rating': 4.7, 'rating_number': 33187, 'price': '8.97', 'subtitle': 'Paperback – US Import, April 27, 2004'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=1853, version=0, score=0.84823483, payload={'main_category': 'Books', 'title': 'A Feast for Crows (A Song of Ice and Fire, Book 4)', 'average_rating': 4.5, 'rating_number': 33402, 'price': '23.99', 'subtitle': 'Hardcover – November 8, 2005'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=706, version=0, score=0.84096694, payload={'main_category': 'Books', 'title': 'Nine Dragons (A Harry Bosch Novel, 14)', 'average_rating': 4.4, 'rating_number': 18634, 'price': '15.91', 'subtitle': 'Hardcover – October 13, 2009'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=1456, version=0, score=0.83784413, payload={'main_category': 'Books', 'title': 'Dune', 'average_rating': 4.7, 'rating_number': 88262, 'price': '9.89', 'subtitle': 'Mass Market Paperback – Unabridged, September 1, 1990'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=1014, version=0, score=0.8347755, payload={'main_category': 'Books', 'title': 'Darkness, Take My Hand: A Novel', 'average_rating': 4.3, 'rating_number': 3670, 'price': '1.35', 'subtitle': 'Mass Market Paperback – July 1, 1997'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=1384, version=0, score=0.83408827, payload={'main_category': 'Books', 'title': 'Harry Potter and the Goblet of Fire (Harry Potter, Book 4) (4)', 'average_rating': 4.9, 'rating_number': 76466, 'price': '18.49', 'subtitle': None}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=338, version=0, score=0.8306421, payload={'main_category': 'Books', 'title': "Bridget Jones's Diary: A Novel", 'average_rating': 4.2, 'rating_number': 4756, 'price': '13.79', 'subtitle': 'Paperback – June 1, 1999'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=389, version=0, score=0.8296001, payload={'main_category': 'Books', 'title': "The Memory Keeper's Daughter: A Novel", 'average_rating': 4.2, 'rating_number': 6046, 'price': '13.48', 'subtitle': 'Paperback – May 30, 2006'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=1112, version=0, score=0.8291641, payload={'main_category': 'Books', 'title': 'Playing For Pizza: A Novel', 'average_rating': 4.3, 'rating_number': 6773, 'price': '14.24', 'subtitle': 'Hardcover – September 24, 2007'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=1500, version=0, score=0.82845485, payload={'main_category': 'Books', 'title': 'Pop Goes the Weasel (Alex Cross, 5)', 'average_rating': 4.5, 'rating_number': 9260, 'price': '8.99', 'subtitle': 'Mass Market Paperback – October 1, 2000'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=475, version=0, score=0.8278457, payload={'main_category': 'Books', 'title': 'World War Z: An Oral History of the Zombie War', 'average_rating': 4.5, 'rating_number': 24188, 'price': '10.35', 'subtitle': 'Paperback – October 16, 2007'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=2360, version=0, score=0.82682836, payload={'main_category': 'Books', 'title': 'The Colorado Kid', 'average_rating': 4.2, 'rating_number': 9310, 'price': 'None', 'subtitle': 'Mass Market Paperback – October 4, 2005'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=1106, version=0, score=0.8248968, payload={'main_category': 'Books', 'title': 'The Innocent Man: Murder and Injustice in a Small Town', 'average_rating': 4.3, 'rating_number': 11651, 'price': '14.34', 'subtitle': 'Hardcover – Illustrated, October 10, 2006'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=7, version=0, score=0.82094646, payload={'main_category': 'Books', 'title': 'Cryptonomicon', 'average_rating': 4.5, 'rating_number': 7826, 'price': '8.99', 'subtitle': 'Mass Market Paperback – Box set, November 5, 2002'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=1107, version=0, score=0.81838757, payload={'main_category': 'Books', 'title': 'The Associate', 'average_rating': 4.4, 'rating_number': 7226, 'price': '9.63', 'subtitle': 'Hardcover – NTSC, January 27, 2009'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=1694, version=0, score=0.81797105, payload={'main_category': 'Books', 'title': 'Lies and the Lying Liars Who Tell Them', 'average_rating': 4.5, 'rating_number': 2211, 'price': '8.8', 'subtitle': 'Hardcover – Import, August 29, 2003'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=1973, version=0, score=0.81721723, payload={'main_category': 'Books', 'title': 'Confederates in the Attic: Dispatches from the Unfinished Civil War', 'average_rating': 4.5, 'rating_number': 1763, 'price': '11.99', 'subtitle': 'Paperback – February 22, 1999'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=1015, version=0, score=0.81512165, payload={'main_category': 'Books', 'title': 'Sacred', 'average_rating': 4.4, 'rating_number': 3160, 'price': '7.99', 'subtitle': None}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=1699, version=0, score=0.8138913, payload={'main_category': 'Books', 'title': 'Caught', 'average_rating': 4.5, 'rating_number': 13022, 'price': '23.59', 'subtitle': 'Hardcover – March 23, 2010'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=671, version=0, score=0.811304, payload={'main_category': 'Books', 'title': 'Breaking Dawn (The Twilight Saga, Book 4)', 'average_rating': 4.7, 'rating_number': 25293, 'price': '14.6', 'subtitle': 'Hardcover – August 2, 2008'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=1191, version=0, score=0.8109874, payload={'main_category': 'Books', 'title': 'A Clockwork Orange', 'average_rating': 4.5, 'rating_number': 9538, 'price': '9.99', 'subtitle': 'Paperback – April 17, 1995'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=1928, version=0, score=0.80952585, payload={'main_category': 'Books', 'title': 'The Empty Chair', 'average_rating': 4.5, 'rating_number': 4050, 'price': '8.36', 'subtitle': 'Mass Market Paperback – April 1, 2001'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=2014, version=0, score=0.8088044, payload={'main_category': 'Books', 'title': 'Miss Julia Speaks Her Mind: A Novel', 'average_rating': 4.4, 'rating_number': 2678, 'price': '13.49', 'subtitle': 'Paperback – August 22, 2000'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=533, version=0, score=0.80858624, payload={'main_category': 'Books', 'title': 'The Sense of an Ending', 'average_rating': 4.0, 'rating_number': 12349, 'price': '4.1', 'subtitle': 'Hardcover – January 1, 2011'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=984, version=0, score=0.8083732, payload={'main_category': 'Books', 'title': 'Empire Falls', 'average_rating': 4.3, 'rating_number': 3042, 'price': '13.58', 'subtitle': 'Paperback – AC-3, April 12, 2002'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=2617, version=0, score=0.8082056, payload={'main_category': 'Books', 'title': "The No. 1 Ladies' Detective Agency (Book 1)", 'average_rating': 4.3, 'rating_number': 6498, 'price': '9.29', 'subtitle': 'Paperback – February 6, 2003'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=1855, version=0, score=0.80720866, payload={'main_category': 'Books', 'title': 'The Taking', 'average_rating': 4.2, 'rating_number': 5761, 'price': '17.0', 'subtitle': 'Hardcover – May 25, 2004'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=2140, version=0, score=0.80492973, payload={'main_category': 'Books', 'title': 'A Memory of Light (Wheel of Time, Book 14) (Wheel of Time, 14)', 'average_rating': 4.8, 'rating_number': 25824, 'price': '20.99', 'subtitle': 'Hardcover – Illustrated, January 8, 2013'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=2789, version=0, score=0.80374503, payload={'main_category': 'Books', 'title': 'Under the Dome: A Novel', 'average_rating': 4.4, 'rating_number': 13280, 'price': '12.0', 'subtitle': 'Paperback – July 6, 2010'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=3303, version=0, score=0.80296826, payload={'main_category': 'Books', 'title': 'The Dark Tower (The Dark Tower, Book 7)', 'average_rating': 4.7, 'rating_number': 11807, 'price': '33.61', 'subtitle': 'Hardcover – September 21, 2004'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=1954, version=0, score=0.8022173, payload={'main_category': 'Books', 'title': 'The Stranger', 'average_rating': 4.5, 'rating_number': 12248, 'price': '11.59', 'subtitle': 'Paperback – March 13, 1989'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=2059, version=0, score=0.80210507, payload={'main_category': 'Books', 'title': 'The Glass Castle: A Memoir', 'average_rating': 4.6, 'rating_number': 39491, 'price': 'None', 'subtitle': 'Hardcover – March 1, 2005'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=89, version=0, score=0.8019334, payload={'main_category': 'Books', 'title': 'Before I Fall', 'average_rating': 4.2, 'rating_number': 7825, 'price': '12.0', 'subtitle': 'Hardcover – March 2, 2010'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=798, version=0, score=0.7996019, payload={'main_category': 'Books', 'title': 'Fahrenheit 451', 'average_rating': 4.6, 'rating_number': 48916, 'price': '7.95', 'subtitle': 'Mass Market Paperback – January 1, 1987'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=704, version=0, score=0.7995324, payload={'main_category': 'Books', 'title': 'The Brass Verdict', 'average_rating': 4.6, 'rating_number': 20602, 'price': '8.58', 'subtitle': 'Hardcover – October 14, 2008'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=1786, version=0, score=0.7988844, payload={'main_category': 'Books', 'title': 'A Game of Thrones (Song of Ice and Fire)', 'average_rating': 4.7, 'rating_number': 72785, 'price': '23.25', 'subtitle': 'Hardcover – August 1, 1996'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=2319, version=0, score=0.7971834, payload={'main_category': 'Books', 'title': 'Crossroads of Twilight (Wheel of Time, Book 10) (Wheel of Time, 10)', 'average_rating': 4.3, 'rating_number': 11651, 'price': '8.08', 'subtitle': 'Mass Market Paperback – November 1, 2003'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=433, version=0, score=0.7971769, payload={'main_category': 'Books', 'title': 'Life Of Pi', 'average_rating': 4.4, 'rating_number': 20909, 'price': '9.39', 'subtitle': 'Paperback – Black & White, May 1, 2003'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=1528, version=0, score=0.79698646, payload={'main_category': 'Books', 'title': 'The Stand: Expanded Edition: For the First Time Complete and Uncut', 'average_rating': 4.6, 'rating_number': 48807, 'price': '8.04', 'subtitle': 'Paperback – May 7, 1991'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=1967, version=0, score=0.7968368, payload={'main_category': 'Books', 'title': 'American Psycho', 'average_rating': 4.4, 'rating_number': 12142, 'price': '12.56', 'subtitle': 'Paperback – March 1, 1991'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=532, version=0, score=0.79671574, payload={'main_category': 'Books', 'title': 'The Expats: A Novel', 'average_rating': 3.9, 'rating_number': 7667, 'price': '19.36', 'subtitle': 'Hardcover – March 6, 2012'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=3130, version=0, score=0.796481, payload={'main_category': 'Books', 'title': 'Water for Elephants: A Novel', 'average_rating': 4.6, 'rating_number': 11740, 'price': '8.39', 'subtitle': 'Paperback – April 9, 2007'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=650, version=0, score=0.796309, payload={'main_category': 'Books', 'title': 'Outliers: The Story of Success', 'average_rating': 4.6, 'rating_number': 35958, 'price': '15.69', 'subtitle': 'Hardcover – Big Book, November 18, 2008'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=40, version=0, score=0.79546344, payload={'main_category': 'Books', 'title': 'Bel Canto', 'average_rating': 4.2, 'rating_number': 11368, 'price': '3.66', 'subtitle': 'Paperback – April 1, 2002'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=659, version=0, score=0.7950983, payload={'main_category': 'Books', 'title': 'Back to Blood: A Novel', 'average_rating': 3.7, 'rating_number': 1313, 'price': '4.21', 'subtitle': 'Hardcover – October 23, 2012'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=285, version=0, score=0.7933484, payload={'main_category': 'Books', 'title': 'The Alchemist: A Fable About Following Your Dream', 'average_rating': 4.6, 'rating_number': 141332, 'price': 'None', 'subtitle': 'Paperback – May 10, 1995'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=2313, version=0, score=0.7931253, payload={'main_category': 'Books', 'title': "Wizard's First Rule (Sword of Truth, Book 1) (Sword of Truth, 1)", 'average_rating': 4.6, 'rating_number': 14017, 'price': 'None', 'subtitle': 'Mass Market Paperback – July 15, 1995'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=738, version=0, score=0.79281783, payload={'main_category': 'Books', 'title': "White Oleander (Oprah's Book Club)", 'average_rating': 4.4, 'rating_number': 4536, 'price': '9.98', 'subtitle': 'Paperback – May 1, 2000'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=1081, version=0, score=0.792704, payload={'main_category': 'Books', 'title': 'Bird by Bird: Some Instructions on Writing and Life', 'average_rating': 4.6, 'rating_number': 7777, 'price': 'None', 'subtitle': 'Paperback – Picture Book, September 1, 1995'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=1605, version=0, score=0.79269314, payload={'main_category': 'Books', 'title': 'Girl with a Pearl Earring: A Novel', 'average_rating': 4.4, 'rating_number': 6689, 'price': '10.25', 'subtitle': None}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=71, version=0, score=0.7926403, payload={'main_category': 'Books', 'title': "What Every Body Is Saying: An Ex-FBI Agent's Guide to Speed-Reading People", 'average_rating': 4.6, 'rating_number': 12204, 'price': '10.99', 'subtitle': 'Paperback – April 15, 2008'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=569, version=0, score=0.79223144, payload={'main_category': 'Books', 'title': 'Chosen (House of Night, Book 3)', 'average_rating': 4.7, 'rating_number': 3131, 'price': '10.36', 'subtitle': 'Paperback – March 4, 2008'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=2053, version=0, score=0.7921288, payload={'main_category': 'Books', 'title': 'Out of the Silent Planet (1) (The Space Trilogy)', 'average_rating': 4.5, 'rating_number': 3685, 'price': 'None', 'subtitle': None}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=632, version=0, score=0.79063463, payload={'main_category': 'Books', 'title': 'The Silence of the Lambs (Hannibal Lecter)', 'average_rating': 4.7, 'rating_number': 8885, 'price': '8.39', 'subtitle': 'Mass Market Paperback – February 15, 1991'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=805, version=0, score=0.790571, payload={'main_category': 'Books', 'title': "The Hitchhiker's Guide to the Galaxy", 'average_rating': 4.4, 'rating_number': 23822, 'price': '6.7', 'subtitle': None}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=1095, version=0, score=0.79053867, payload={'main_category': 'Books', 'title': 'The Lost Symbol (Robert Langdon)', 'average_rating': 4.3, 'rating_number': 28905, 'price': '9.91', 'subtitle': 'Hardcover – Illustrated, September 15, 2009'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=1331, version=0, score=0.7904339, payload={'main_category': 'Books', 'title': 'Without Remorse (John Clark Novel, A)', 'average_rating': 4.6, 'rating_number': 11903, 'price': '9.99', 'subtitle': 'Mass Market Paperback – August 1, 1994'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=1489, version=0, score=0.7901872, payload={'main_category': 'Books', 'title': 'Wild Fire', 'average_rating': 4.5, 'rating_number': 5888, 'price': 'None', 'subtitle': 'Hardcover – CLV, November 6, 2006'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=482, version=0, score=0.78994364, payload={'main_category': 'Books', 'title': 'Into the Wild', 'average_rating': 4.4, 'rating_number': 19218, 'price': '10.81', 'subtitle': 'Paperback – Abridged, August 21, 2007'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=1881, version=0, score=0.7886554, payload={'main_category': 'Books', 'title': 'Execution: The Discipline of Getting Things Done', 'average_rating': 4.4, 'rating_number': 1397, 'price': '9.99', 'subtitle': 'Hardcover – June 15, 2002'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=2689, version=0, score=0.7882157, payload={'main_category': 'Books', 'title': 'The Dark Tower VI: Song of Susannah (6) (The Dark Tower, Book 6)', 'average_rating': 4.5, 'rating_number': 9608, 'price': '8.06', 'subtitle': 'Mass Market Paperback – June 1, 2006'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=1892, version=0, score=0.7877645, payload={'main_category': 'Books', 'title': 'The Worst Hard Time: The Untold Story of Those Who Survived the Great American Dust Bowl', 'average_rating': 4.4, 'rating_number': 5684, 'price': '11.99', 'subtitle': 'Paperback – September 1, 2006'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=839, version=0, score=0.78721213, payload={'main_category': 'Books', 'title': 'Embassytown', 'average_rating': 4.2, 'rating_number': 1609, 'price': '27.32', 'subtitle': 'Hardcover – May 17, 2011'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=491, version=0, score=0.7869339, payload={'main_category': 'Books', 'title': 'The Girl with the Dragon Tattoo (The Girl with the Dragon Tattoo Series)', 'average_rating': 4.5, 'rating_number': 31377, 'price': '10.99', 'subtitle': 'Paperback – June 23, 2009'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=1918, version=0, score=0.78609514, payload={'main_category': 'Books', 'title': 'The Gunslinger (The Dark Tower, Book 1)', 'average_rating': 4.3, 'rating_number': 29995, 'price': 'None', 'subtitle': 'Hardcover – June 23, 2003'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=1008, version=0, score=0.7860322, payload={'main_category': 'Books', 'title': "Dash & Lily's Book of Dares", 'average_rating': 4.3, 'rating_number': 2543, 'price': 'None', 'subtitle': 'Hardcover – January 2, 2010'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=1956, version=0, score=0.7847719, payload={'main_category': 'Books', 'title': 'The Maltese Falcon', 'average_rating': 4.3, 'rating_number': 5156, 'price': '10.22', 'subtitle': 'Paperback – August 1, 1992'}, vector=None, shard_key=None, order_value=None),